name: Android CI

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - uses:  actions/checkout@v2
      - name:  set up JDK 1.8
        uses:  actions/setup-java@v1
        with:
          java-version:  1.8
      - name:  build with gradle
        run: |
          echo "当前执行命令目录如下 》"
          pwd
          echo "去除 \r 字符 》"
          sed -i 's/\r//' gradlew
          echo "执行 task 进行打包"
          chmod +x gradlew
          ./gradlew assemblePeaceRelease
      - name:  upload apk
        uses:  actions/upload-artifact@master
        if:  always()
        with:
          name:  showu-release-outputs
          path: ${{github.workspace}}/app/build/outputs
  
